/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include <iostream>
int main()
{
 int f1=1,f2=2;
 int sum=0,value =2;
 while(sum < 4000000)
{
 sum = f1 + f2;
 f1 = f2;
 f2 = sum;
 if (sum%2 == 0)
   value = value + sum;
}
std::cout<<value<<std::endl;
}

